name: learn-github-actions
on:
  workflow_dispatch:
jobs:
  check-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - run: |
          echo '${{ steps.package-version.current-version}}'
